[package]
name = "num-rs"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettytable-rs = "0.9.0"
structopt = "0.3"

[[bin]]
name = "num"
path = "src/main.rs"